# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
   - name: JiebaTokenizer
     dictionary_path: "dictionary/"
     # Flag to check whether to split intents
     "intent_tokenization_flag": False
     # Symbol on which intent should be split
     "intent_split_symbol": "_"
     # Regular expression to detect tokens
     "token_pattern": None

   - name: RegexFeaturizer
     use_word_boundaries: False
     use_lookup_tables: True
     use_regexes: True
   - name: LexicalSyntacticFeaturizer
   - name: LanguageModelFeaturizer
     model_name: bert
     model_weights: bert-base-chinese
   - name: DIETClassifier

     epochs: 200
     batch_size: 32
     learning_rate: 0.001
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

policies:
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
   - name: RulePolicy